- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - openstack-python-jobs
      - openstack-python35-jobs
      - lib-forward-testing
      - release-notes-jobs-python3
